Add_Friends/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'add_friend/$', add_friend, name='add_friend'),
]

Post/urls.py
from django.conf.urls import url
from .views import index,post

urlpatterns = [
	url(r'^$', index, name='index'),#TODO Implement this
	url(r'^posting/',post,name='post'),
]

Tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import stats.urls as stats
import Post.urls as Post
import Add_Friends.urls as Add_Friends
import profile_page.urls as profile_page
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Post/',include(Post,namespace='Post')),
    url(r'^stats/', include(stats,namespace='stats')),
    url(r'^$',RedirectView.as_view(url="/Post/",permanent="true")),
    url(r'^Add-Friends/', include(Add_Friends,namespace='Add-Friends')),
    url(r'^profile/', include(profile_page,namespace='profile_page')),
]

profile_page/urls.py
from django.conf.urls import url
from .views import index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

Add_Friends/models.py
from django.db import models

class Friends(models.Model):
	name = models.CharField(max_length = 60)
	link = models.URLField(max_length = 200)
	time = models.DateTimeField(auto_now_add=True)

# Create your models here.

Post/models.py
from django.db import models

# Create your models here.
class MakePost(models.Model):
	description = models.CharField(max_length=1600)
	created_date = models.DateTimeField(auto_now_add=True)

profile_page/models.py
from django.db import models

# Create your models here.
class DataProfile(models.Model):
    Name = models.CharField(max_length=250, default="No Name")
    Birthday = models.CharField(max_length=25, default="1 Januari 1990")
    Gender = models.CharField(max_length=15, default="Not Specified")
    Expertise = models.TextField(max_length=200, default="No Expert")
    Description = models.CharField(max_length=200, default="No Description")
    Email = models.CharField(max_length=200, default="...@gmail.com")

stats/models.py
from django.db import models

# Create your models here.

Add_Friends/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan link',
    }
    name_attrs = {
        'class': 'form-control',
        'placeholder': 'your friend name'
    }
    link_attrs = {
        'class': 'form-control',
        'placeholder': 'your firend link'
    }

    name = forms.CharField(label='Name',required=True, max_length=90,error_messages=error_messages, 
    	widget=forms.TextInput(attrs=name_attrs))
    link = forms.CharField(label='Link',required= False,max_length=90,error_messages=error_messages, 
    	widget=forms.TextInput(attrs=link_attrs))

Post/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi post ini',
    }
    post_attrs = {
        'cols': 160,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Apa yang anda pikirkan?'
    }



    post = forms.CharField(error_messages=error_messages,label='', required=True, widget=forms.Textarea(attrs=post_attrs))

Add_Friends/views.py
from django.shortcuts import render, redirect
from .models import Friends
from .forms import Add_Friend_Form
from django.http import HttpResponseRedirect
import pytz
import json

# Create your views here.
my_friends = {}
mhs_name = 'Luthfi Ferdian'
response = {}
def index(request):
    my_friends = Friends.objects.all().values()
    response['add_friend_form'] = Add_Friend_Form
    response['my_friends'] = my_friends
    response['author'] = mhs_name
    return render(request, 'Add_Friends.html', response)


def add_friend(request):
    form = Add_Friend_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['link'] = request.POST['link'] if request.POST['link'] != "" else "Anonymous"
        friend = Friends(name=form.cleaned_data['name'], link=form.cleaned_data['link'])
        friend.save()
        return HttpResponseRedirect('/Add-Friends/')
    else:
        response['form'] = form
    html ='friend_result.html'
    friend = Friends.objects.all()
    response['friend'] = friend
    return HttpResponseRedirect('/Add-Friends/')

Post/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import MakePost
# Create your views here.
mhs_name="Pasu Siahaan"
response = {}
def index(request):
    response ['Message_Form']= Message_Form #messsage
    make_post = MakePost.objects.all()
    response['name']='Luke Skywalker'
    response ['author']= mhs_name
    response['make_post']= make_post
    html = 'Post/Post.html'
    return render(request,html,response)
def post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['make_post'] = request.POST['post']
        make_post = MakePost(description=response['make_post'])
        make_post.save()
        return HttpResponseRedirect('/Post/')
    else:
        return HttpResponseRedirect('/Post/')

profile_page/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import DataProfile

# Create your views here.
mhs_name = 'Saffana Dira Qanya'
user_name = 'Luke Skywalker'
birth_date = date(1998,12,31)
birthdate = birth_date.strftime('%d %B %Y')
gender = 'Male'
desc_user = ' i am a human male Jedi Master who was instrumental in defeating the Galactic Empire and the Sith during the Galactic Civil War. '
exp_user = ["Force User", "Light-Saber mastery", "X-wing starfighter pilot"]
email = 'Luke.skywalker@rebellion.com'
profile = DataProfile(Name = user_name, Birthday = birthdate, Gender= gender, Description = desc_user, Expertise = exp_user, Email = email)

def index(request):
    response= {'profile': profile, 'author' : mhs_name}
    return render(request, 'profile/profile.html', response)

stats/views.py
from django.shortcuts import render
from Post.models import MakePost
from Add_Friends.models import Friends
from profile_page.models import DataProfile

response = {}
def index(request):
    response['Name'] = "Luke Skywalker"
    response['totalFriends']=len(Friends.objects.all())
    stat=MakePost.objects.all().order_by('-created_date')
    jumlahPost=len(MakePost.objects.all())
    response['totalPost']=jumlahPost
    jumlahPost=len(stat)
    if (jumlahPost!=0):
        response['recentPost']=stat[0]
        response['totalPost']=jumlahPost
    else:
        response['totalPost']=0

    return render(request, 'stats/stats.html', response)

Add_Friends/templates/Add_Friends.html
{% extends "layout/base.html" %}
{% block content %}

 <div class="container">
<section>
	<h3>Add friends</h3>
	<br>
	<section name="form">
        <form id="form" method="POST" action="{% url 'Add-Friends:add_friend' %}">
            {% csrf_token %}
            {{ add_friend_form }}
            <br>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </section>
<section>
<table class="table">
        <thead>
            <th>Nama</th>
            <th>Link</th>
            <th align-content="right" >Ditambahkan Pada</th>
        </thead>
        <tbody>
            <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
            {% for friends_data in my_friends %}
            {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
            <tr class="warning"> {% else %} <tr class="success">
                {% endif %}
                <td> {{ friends_data.name }} </td>
                <td> {{ friends_data.link }} </td>
                <td align="right"> {{ friends_data.time }} </td>
            </tr>             
            {% endfor %}
        </tbody>
</table>
</section>
</div>
{% endblock %}

Add_Friends/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Add-Friends">
    <meta name="author" content="{{author}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <!-- bootstrap csss -->

    <title>
        {% block title %} Friends By {{author}} {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
</body>
</html>

Add_Friends/templates/partials/footer.html
<style>

.copyright { min-height:40px; background-color:#000000;}
.copyright p { text-align:left; color:#FFF; padding:10px 0; margin-bottom:0px;}

</style>

<div class="copyright">
  <div class="container">
    <div class="col-md-6">
      <p>© 2017 - Team 2D</p>
    </div>
  </div>
</div>

Add_Friends/templates/partials/header.html
s<!-- Fixed navbar -->
 <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
     <div class="navbar-header">
     </div>
     <div align="center">

       <ul class="nav navbar-nav navbar-right">
         <li><a href="/Post/">Status</a></li>
         <li><a href="/profile/">Profile</a></li>
         <li class="active"><a href="/Add-Friends/">Friends</a></li>
         <li><a href="/stats/">Stats</a></li>
       </ul>
     </div><!--/.nav-collapse -->
   </div>
 </div>

 <div class="container-fluid big-logo-row">
   <div class="container">
     <div class="row">
       <div class="col-xs-12 big-logo-container">
         <h1 class="big-logo">LingIn</h1>
       </div><!--/.col-xs-12 -->
     </div><!--/.row -->
   </div><!--/.container -->
 </div><!--/.container-fluid -->

Post/templates/Post/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Post">
    <meta name="author" content="{{author}}">
    <meta name="name" content="{{name}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Post.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <!-- bootstrap csss -->

    <title>
        {% block title %} Update Status By {{author}} {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "Post/partials/header.html" %}
    </header>
    <content>
            {% block content %}

            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "Post/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
   
</body>
</html>

Post/templates/Post/partials/footer.html
<style>

.copyright { min-height:40px; background-color:#000000; bottom: 0}
.copyright p { text-align:left; color:#FFF; padding:10px ; margin-bottom:15px; bottom: 0}

</style>

<div class="copyright">
  <div class="container">
    <div class="col-md-6">
      <p>© 2017 - Team 2D</p>
    </div>
  </div>
</div>

Post/templates/Post/partials/header.html
s<!-- Fixed navbar -->
 <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
     <div class="navbar-header">
     </div>
     <div align="center">

       <ul class="nav navbar-nav navbar-right">
         <li  class="active"><a href="/Post/">Status</a></li>
         <li><a href="/profile/">Profile</a></li>
         <li><a href="/Add-Friends/">Friends</a></li>
         <li><a href="/stats/">Stats</a></li>
       </ul>
     </div><!--/.nav-collapse -->
   </div>
 </div>

 <div class="container-fluid big-logo-row">
   <div class="container">
     <div class="row">
       <div class="col-xs-12 big-logo-container">
         <h1 class="big-logo">LingIn</h1>
       </div><!--/.col-xs-12 -->
     </div><!--/.row -->
   </div><!--/.container -->
 </div><!--/.container-fluid -->

profile_page/templates/profile.html
{% extends "profile/layout/base.html" %}
{% block content %}

<br><br><br>

<section name="profile" style="margin-bottom:50px">
    <div class="container">
    	<h1>Profile</h2>
    </div>
    <div class="data"=>
      <h2 style="text-align:center">{{profile.Name}}</h2>
      <div  align="center"> <img alt="User Pic" src="https://vignette1.wikia.nocookie.net/starwars/images/c/cf/Luke_Skywalker_Exiled.png/revision/latest?cb=20160416224618" id="profile-image1" width="150" height="150" class="img-circle img-responsive">
    </div>
    <div class="biodata">
        <table align="center" width="500" cellspacing = "40" cellpadding="40" style="text-align: left">
          <br><br>
            <tr>
              <td class="subject">Birthday</td>
              <td class="value">{{profile.Birthday}}</td>
            </tr>
            <tr>
              <td class="subject">Gender</td>
              <td class="value">{{profile.Gender}}</td>
            </tr>
            <tr>
              <td class="subject">Expertise</td>
              <td class="value">
                <ul>
                {% for ii in profile.Expertise %}
                <button type="button" class="btn btn-inverse" data-dismiss="modal">{{ii}}</button>
                {% endfor %}
              </ul>
            </td>
          </tr>
          <tr>
            <td class="subject" >Description</td>
            <td class="value" >{{profile.Description}}</td>
          </tr>
          <tr>
            <td class="subject" >Email</td>
            <td class="value" >{{profile.Email}}</td>
          </tr>
        </table>
    </div>
</section>


<br><br>

{% endblock %}

profile_page/templates/profile/partials/footer.html
<style>

.copyright { min-height:40px; background-color:#000000;}
.copyright p { text-align:left; color:#FFF; padding:10px 0; margin-bottom:0px;}

</style>

<div class="copyright">
  <div class="container">
    <div class="col-md-6">
      <p>© 2017 - Team 2D</p>
    </div>
  </div>
</div>

profile_page/templates/profile/partials/header.html
s<!-- Fixed navbar -->
 <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
     <div class="navbar-header">
     </div>
     <div align="center">

       <ul class="nav navbar-nav navbar-right">
         <li><a href="/Post/">Status</a></li>
         <li class="active"><a href="/profile/">Profile</a></li>
         <li><a href="/Add-Friends/">Friends</a></li>
         <li><a href="/stats/">Stats</a></li>
       </ul>
     </div><!--/.nav-collapse -->
   </div>
 </div>

 <div class="container-fluid big-logo-row">
   <div class="container">
     <div class="row">
       <div class="col-xs-12 big-logo-container">
         <h1 class="big-logo">LingIn</h1>
       </div><!--/.col-xs-12 -->
     </div><!--/.row -->
   </div><!--/.container -->
 </div><!--/.container-fluid -->

profile_page/templates/profile/profile.html
{% extends "profile/layout/base.html" %}
{% block content %}

<br><br><br>

<section name="profile" style="margin-bottom:50px">
    <div class="container">
    	<h1>Profile</h2>
    </div>
    <div class="data"=>
      <h2 style="text-align:center">{{profile.Name}}</h2>
      <div  align="center"> <img alt="User Pic" src="https://vignette1.wikia.nocookie.net/starwars/images/c/cf/Luke_Skywalker_Exiled.png/revision/latest?cb=20160416224618" id="profile-image1" width="150" height="150" class="img-circle img-responsive">
    </div>
    <div class="biodata">
        <table align="center" width="500" cellspacing = "40" cellpadding="40" style="text-align: left">
          <br><br>
            <tr>
              <td class="subject">Birthday</td>
              <td class="value">{{profile.Birthday}}</td>
            </tr>
            <tr>
              <td class="subject">Gender</td>
              <td class="value">{{profile.Gender}}</td>
            </tr>
            <tr>
              <td class="subject">Expertise</td>
              <td class="value">
                <ul>
                {% for ii in profile.Expertise %}
                <button type="button" class="btn btn-inverse" data-dismiss="modal">{{ii}}</button>
                {% endfor %}
              </ul>
            </td>
          </tr>
          <tr>
            <td class="subject" >Description</td>
            <td class="value" >{{profile.Description}}</td>
          </tr>
          <tr>
            <td class="subject" >Email</td>
            <td class="value" >{{profile.Email}}</td>
          </tr>
        </table>
    </div>
</section>


<br><br>

{% endblock %}

stats/templates/stats/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>



<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Stats">
    <meta name="author" content="{{author}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'css/Post.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <!-- bootstrap csss -->

    <title>
        {% block title %} Status page By {{author}} {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "stats/partials/header.html" %}
    </header>
    <content>
            {% block content %}

            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "stats/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script></script>

</body>
</html>

stats/templates/stats/partials/footer.html
<style>

.copyright { min-height:40px; background-color:#000000; bottom: 0}
.copyright p { text-align:left; color:#FFF; padding:10px ; margin-bottom:15px; bottom: 0}

</style>

<div class="copyright">
  <div class="container">
    <div class="col-md-6">
      <p>© 2017 - Team 2D</p>
    </div>
  </div>
</div>

stats/templates/stats/partials/header.html
s<!-- Fixed navbar -->
 <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
     <div class="navbar-header">
     </div>
     <div align="center">

       <ul class="nav navbar-nav navbar-right">
         <li><a href="/Post/">Status</a></li>
         <li><a href="/profile/">Profile</a></li>
         <li><a href="/Add-Friends/">Friends</a></li>
         <li class="active"><a href="/stats/">Stats</a></li>
       </ul>
     </div><!--/.nav-collapse -->
   </div>
 </div>

 <div class="container-fluid big-logo-row">
   <div class="container">
     <div class="row">
       <div class="col-xs-12 big-logo-container">
         <h1 class="big-logo">LingIn</h1>
       </div><!--/.col-xs-12 -->
     </div><!--/.row -->
   </div><!--/.container -->
 </div><!--/.container-fluid -->